# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a5d0a7aaa61e68444f2ffc28026d21405a06939fe93e9758ebf6b7996aa29bba7440485ed9fddcec7cbd9128e7b9ec83981c2ce03c2c888893435001140103b

test:
  secret_key_base: 3e4ec39dafc585b2b5c14ced0545ae6b4c7cf88a89ba471a7ad2b0a52e035f23d49b4acdb3f1d30ea172aafac21aa811e5be97aab5c588d40317285baea56737

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
